# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1400, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 850))
        MainWindow.setMaximumSize(QtCore.QSize(1400, 850))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1020, 350, 361, 441))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_log = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_log.setContentsMargins(0, 0, 0, 0)
        self.layout_log.setObjectName("layout_log")
        self.title_log = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title_log.setFont(font)
        self.title_log.setAlignment(QtCore.Qt.AlignCenter)
        self.title_log.setObjectName("title_log")
        self.layout_log.addWidget(self.title_log)
        self.canvas_log = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.canvas_log.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.canvas_log.setFont(font)
        self.canvas_log.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.canvas_log.setObjectName("canvas_log")
        self.layout_log.addWidget(self.canvas_log)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.btn_record_img = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_record_img.setStyleSheet("QPushButton:hover { \n"
"  background-color: rgbd(155,155,155,155);\n"
"}\n"
"\n"
"QPushButton{\n"
"    selection-color: rgb(255, 255, 127);\n"
"    background-color: rgbd(255, 49, 8, 190);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;       \n"
"    border-width: 1px;    \n"
"    border-color: beige;  \n"
"    border-radius: 5px; \n"
"    selection-background-color: rgb(255, 170, 127);\n"
"    focus{background-color: red};\n"
"}\n"
"\n"
"QPushButton:disabled { \n"
"    background-color: rgbd(155,155,155,50);\n"
"}")
        self.btn_record_img.setCheckable(False)
        self.btn_record_img.setChecked(False)
        self.btn_record_img.setAutoDefault(False)
        self.btn_record_img.setObjectName("btn_record_img")
        self.horizontalLayout1.addWidget(self.btn_record_img)
        self.btn_record_pc_img = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_record_pc_img.setStyleSheet("QPushButton:hover { \n"
"  background-color: rgbd(155,155,155,155);\n"
"}\n"
"\n"
"QPushButton{\n"
"    selection-color: rgb(255, 255, 127);\n"
"    background-color: rgbd(255, 49, 8, 190);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;       \n"
"    border-width: 1px;    \n"
"    border-color: beige;  \n"
"    border-radius: 5px; \n"
"    selection-background-color: rgb(255, 170, 127);\n"
"    focus{background-color: red};\n"
"}\n"
"\n"
"QPushButton:disabled { \n"
"    background-color: rgbd(155,155,155,50);\n"
"}")
        self.btn_record_pc_img.setCheckable(False)
        self.btn_record_pc_img.setChecked(False)
        self.btn_record_pc_img.setAutoDefault(False)
        self.btn_record_pc_img.setObjectName("btn_record_pc_img")
        self.horizontalLayout1.addWidget(self.btn_record_pc_img)
        self.layout_log.addLayout(self.horizontalLayout1)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.btn_is_img_ready = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_is_img_ready.setEnabled(True)
        self.btn_is_img_ready.setStyleSheet("QPushButton:hover { \n"
"  background-color: rgbd(155,155,155,155);\n"
"}\n"
"\n"
"QPushButton{\n"
"    selection-color: rgb(255, 255, 127);\n"
"    background-color: rgbd(255, 49, 8, 190);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;       \n"
"    border-width: 1px;    \n"
"    border-color: beige;  \n"
"    border-radius: 5px; \n"
"    selection-background-color: rgb(255, 170, 127);\n"
"    focus{background-color: red};\n"
"}\n"
"\n"
"QPushButton:disabled { \n"
"    background-color: rgbd(155,155,155,50);\n"
"}")
        self.btn_is_img_ready.setCheckable(False)
        self.btn_is_img_ready.setChecked(False)
        self.btn_is_img_ready.setDefault(False)
        self.btn_is_img_ready.setObjectName("btn_is_img_ready")
        self.horizontalLayout2.addWidget(self.btn_is_img_ready)
        self.placeholder = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.placeholder.setText("")
        self.placeholder.setObjectName("placeholder")
        self.horizontalLayout2.addWidget(self.placeholder)
        self.layout_log.addLayout(self.horizontalLayout2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1020, 20, 361, 311))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_img = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_img.setContentsMargins(0, 0, 0, 0)
        self.layout_img.setObjectName("layout_img")
        self.title_img = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.title_img.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title_img.setFont(font)
        self.title_img.setAlignment(QtCore.Qt.AlignCenter)
        self.title_img.setObjectName("title_img")
        self.layout_img.addWidget(self.title_img)
        self.canvas_img = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.canvas_img.setMinimumSize(QtCore.QSize(0, 90))
        self.canvas_img.setText("")
        self.canvas_img.setObjectName("canvas_img")
        self.layout_img.addWidget(self.canvas_img)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Collection"))
        self.title_log.setText(_translate("MainWindow", "Log"))
        self.canvas_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans Mono\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Noto Sans Yi\'; font-weight:400;\"><br /></p></body></html>"))
        self.btn_record_img.setText(_translate("MainWindow", "Record Image"))
        self.btn_record_pc_img.setText(_translate("MainWindow", "Record Pointcloud && Image"))
        self.btn_is_img_ready.setText(_translate("MainWindow", "isImageReady"))
        self.title_img.setText(_translate("MainWindow", "Image"))
